#
# Copyright (c) 1/22/15 8:50 PM.Nth Dimenzion, Inc - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
#

server:
  port: 6443
  context-path: /pla

spring:
  thymeleaf:
      check-template-location: true
      cache: false
      mode: XHTML

  jpa:
      hibernate:
        ddl-auto: update
      database: MYSQL
      show-sql: true

  profiles:
        active: ${spring.profiles.active}

  smeServer :
        logoutUrl: https://5.9.249.195:7443/myportal/control/logout
        dev :
          url : http://localhost:6443/pla/stub
        prod :
          url: http://5.9.249.195:9090/partymgr/control

  datasource:
      primary:
        name: primaryDataSource
        url: jdbc:mysql://localhost:3306/pla?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&rewriteBatchedStatements=true&autoReconnect=true
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: welcome

      jobs:
        name: jobsDataSource
        url: jdbc:mysql://localhost:3306/plajobs?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&rewriteBatchedStatements=true&autoReconnect=true
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: welcome
flyway:
  check-location: true
  enabled: true
